name: Deploy

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     
     - name: setup node env
       uses: actions/setup-node@v2
       with:
        node-version: '14'
     
     - name: build front end
       working-directory: ./capstone-client
       run: |
            npm install
            npm run build:prod
            
     - name: build and start spring server
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.SERVER_PROJECT_DIR }}/capstone-server
          ./mvnw package -Dmaven.test.skip=true
          ./mvnw spring-boot:stop
          nohup ./mvnw spring-boot:run &>/dev/null
          echo "i was here" >> here.txt
          exit
          
     
     - name: copy angular build files via scp
       uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        rm: true
        source: "./capstone-client/dist"
        target: "${{ secrets.SERVER_PROJECT_DIR }}/capstone-client/dist"

           
