name: Deploy to server

on: 
 push: 
   branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v2
     
     - name: setup NodeJs 14
       uses: actions/setup-node@v2
       with:
        node-version: '14'
     
     - name: setup JDK 8
       uses: actions/setup-java@v2
       with:
          java-version: '8'
          distribution: 'adopt'
          
     - name: build backend
       working-directory: ./capstone-server
       run: |
            sudo chmod +x ./mvnw
            ./mvnw package -Dmaven.test.skip=true
     
     - name: build front end
       working-directory: ./capstone-client
       run: |
            npm install
            npm run build:prod
            
     - name: stop spring server and delete previous build files
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.SERVER_PROJECT_DIR }}
          git pull origin main
          cd capstone-server
          ./mvnw spring-boot:stop
          rm -rf {{ secrets.SERVER_PROJECT_DIR }}/capstone-server/target
          rm -rf {{ secrets.SERVER_PROJECT_DIR }}/capstone-client/dist
          
     - name: upload backend build files
       uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "capstone-server/target/*"
        target: "${{ secrets.SERVER_PROJECT_DIR }}"
            
     - name: restart spring server
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.SERVER_PROJECT_DIR }}/capstone-server
          ./mvnw dependency:resolve
          nohup ./mvnw spring-boot:start &>/dev/null
  
     
     - name: copy frontend build files
       uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "capstone-client/dist/*"
        target: "${{ secrets.SERVER_PROJECT_DIR }}"

           
